Fix urls.py
TypeError: 'RegexURLResolver' object is not iterable

This error occurred at line number 22 because += only works on iterables. Must have been a typo.